# Methodology {#sec-methodology}

In order to address the research questions defined in @sec-research-questions--goals, we first need to define a suitable methodology. From a high-level perspective, a machine learning workflow follows the following steps:

1.  Problem understanding and definition
2.  Data preparation and cleaning
3.  Exploratory data analysis (EDA)
4.  Data preprocessing and feature engineering
5.  Modelling
    1.  Model development and training

    2.  Model evaluation
6.  Model selection and deployment

However, the above steps are usually not carried out in a linear manner. Usually, a first comparison evaluation of models leads to a better understanding of the data and can provide new ideas for more feature engineering steps. @fig-modelling-process provides a overview of a typical modelling process.

![A schematic for the typical modeling process [@silge].](figures/03-fig-modelling-process.png){#fig-modelling-process}

In the following subsections of this chapter, we will discuss the steps listed above in the context of the present study.

## Data unterstanding and exploration {#sec-data-unterstanding-and-exploration}

The dataset that we use for modelling is the result of merging information from various sources. @tbl-data-sources provides a overview of the data sources used for the project.

| **Data/Information**                   | **Spatial resolution**         | **Temporal resolution**      | **Source**                                                                                                                                                                                                                                 | **Owner**                                               |
|----------------------------------------|--------------------------------|------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------|
| Building characteristics               | Building                       | Yearly (2016, 2018, 2020)    | [Cantonal register of buildings and dwellings](https://www.baselland.ch/politik-und-behorden/direktionen/finanz-und-kirchendirektion/statistisches-amt/register/gebaeude-und-wohnungsregister-gwr)                                         | Statistisches Amt des Kantons-Basel Landschaft (STA BL) |
| Energy consumption                     | Building                       | Yearly (2016, 2018, 2020)    | [Cantonal energy statistics](https://www.statistik.bl.ch/web_portal/8)                                                                                                                                                                     | STA BL                                                  |
| Inhabitants per buidling               | Building                       | Quarterly (2016, 2018, 2020) | [Cantonal population statistics](https://www.statistik.bl.ch/web_portal/1)                                                                                                                                                                 | STA BL                                                  |
| Demographic characteristics            | Raster grid (mesh size 100 m)  | Yearly (2016, 2018, 2020)    | [Population and Households Statistics (STATPOP)](https://www.bfs.admin.ch/bfs/en/home/statistics/population/surveys/statpop.assetdetail.22406439.html)                                                                                     | Bundesamt für Statistik (BFS)                           |
| Retrofit information                   | Building                       | Daily (2009-2020)            | [Baselbieter Energiepaket](https://www.energiepaket-bl.ch/)                                                                                                                                                                                | Amt für Umwelschutz und Energie (AUE BL)                |
| Elevation information                  | Raster grid (mesh size 0.25 m) | 2021                         | [Digital elevation model (DEM)](https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-geoinformation/geoportal/geodaten/geodatenprodukte/hoehenmodelle/digitales-terrain-modell-dtm) | Amt für Geoinformation (AGI BL)                         |
| Building floor plan[^03-methodology-1] | Building                       | Daily (2016, 2018, 2020)     | [Cantonal cadastral survey](https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-geoinformation/amtliche-vermessung)                                                                | Amt für Geoinformation (AGI BL)                         |

: Overview of data sources {#tbl-data-sources}

[^03-methodology-1]: The building floor plan servers as basis to calculate the distance to the next building and therby extract the information if a building is stand-alone or directly connected to another buidling.

## Data preparation {#sec-data-prep}

In order to prepare the data for modelling, we apply the following filters:

-   Only residential buildings (`gkat = 1020`)
-   Only buildings with a HEPI \> 20 kWh/m² or HEPI \<300 kWh/m²
-   Only buildings where the gas is used for HEC or for DWH+HEC. As this information is absent for many buildings, we also include `NA` values here.

## Modelling {#sec-modelling}

### Algorithms {#sec-algorithms}

The following algorithms are considered in the modelling process:

...

### Modelling workflow

The modelling workflow of the present study is guided by the research questions as defined in @sec-research-questions. The modelling process consists of three steps: In a first step, all the available buildings after applying the filters defined in @sec-data-prep will be used for modelling. After splitting the data into a test and training set, we will train different models on our training data and evaluate and compare the results of the models based on the metrics defined in @sec-evaluation-metrics (see @fig-model-exploration).

```{mermaid}
%%| fig-cap: "Step 1: Model exploration."
%%| label: fig-model-exploration
%%| fig-width: 6
%%{init: {'theme': 'neutral'}}%%
graph TD
    A[Initial data] -->|Preprocessing| B(Training data 80%)
    A -->|Preprocessing| C(Test data 20%) 
    style A B C fill:#f7cac9,stroke:#333,stroke-width:2px
    B --> D[Variable selection]
    D --> E[Multiple linear regression]
    D --> F[Random forest]
    D --> G[Artificial neural network]
    D --> H[...other models...]
    E --> I(Model evaluation) 
    F --> I 
    G --> I
    H --> I 
    style D fill:#d5f5e3,stroke:#333,stroke-width:2px
    style E F G H fill:#fff2cc,stroke:#333,stroke-width:2px
    style I fill:#2ac470,stroke:#333,stroke-width:2px

```

Subsequently in a second step, the best model of the first step will be used to train on different subsets of the data. This allows as to focus on subquestion 1.2 defined in @sec-research-questions.

```{mermaid}
%%| fig-cap: "Step 2: Model on subsets."
%%| label: fig-model-subsets
%%| fig-width: 6
%%{init: {'theme': 'neutral'}}%%
graph TD
    A(Initial data) -->|Preprocessing| B(Training data 80%)
    A -->|Preprocessing| C(Test data 20%) 
    B --> D(Data subsets)
    D --> E(Building class)
    D --> F(Municipality)
    D --> G(Construction period)
    E --> I(Best model step 1) 
    F --> I 
    G --> I
    I --> H(Model evaluation)
    C --> H

    style A fill:#f7cac9,stroke:#333,stroke-width:2px
    style D fill:#d5f5e3,stroke:#333,stroke-width:2px
    style I fill:#2ac470,stroke:#333,stroke-width:2px
    style H fill:#fff2cc,stroke:#333,stroke-width:2px
```

Finally, the last step of the modelling process consists of comparing the final model(s) of the previous steps with the current approach. Furthermore, a sensitivity analysis will be carried out in order to understand what input variables are most important in the final model (see @fig-model-compare-sensitivity).

```{mermaid}
%%| fig-cap: "Step 3: Compare predictions to current approach and sensitivity analysis."
%%| label: fig-model-compare-sensitivity
%%| fig-width: 6
%%{init: {'theme': 'neutral'}}%%
graph TD
    A(Final model) -->|apply on| B(Test data )
    B --> C(Predictions  )
    C --> D(<b>Evaluation</b>: <br>Compare to current approach)
    C --> E(<b>Sensitivity analysis:</b><br>What features are most important?)
    style A fill:#f7cac9,stroke:#333,stroke-width:2px
    style D fill:#d5f5e3,stroke:#333,stroke-width:2px
    style E fill:#d5f5e3,stroke:#333,stroke-width:2px
```

{{< pagebreak >}}

### Model tuning

## Evaluation metrics {#sec-evaluation-metrics}

For evaluation and comparison of the different models, we will use the following metrics:

-   Root mean squared error (RMSE)
-   Mean absolute error (MAE)
-   Mean absolute percentage error (MAPE)
-   R-Squared ($R²$)

In the following, we will present the mathematical formula and a short explanation of the metrics that will be used for evaluation.

#### RMSE

The Root mean squared error (RMSE) is a measure of the differences between predicted and actual values. It is calculated by taking the square root of the mean of the squared differences between predicted and actual values. The formula for RMSE is given as:

$$ RMSE = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y_i})^2} $$

where $y_i$ represents the actual values, $\hat{y_i}$ represents the predicted values and $n$ represents the number of samples.

### MAE

The Mean absolute error (MAE) is another measure of the differences between predicted and actual values. Unlike RMSE, it is not squared, so it is less sensitive to outliers. It is calculated as the average of the absolute differences between predicted and actual values. The formula for MAE is given as:

$$ MAE = \frac{1}{n} \sum_{i=1}^{n} \left| y_i - \hat{y_i} \right| $$

where $y_i$ represents the actual values, $\hat{y_i}$ represents the predicted values and $n$ represents the number of samples.

### MAPE

The Mean absolute percentage error (MAPE) is a measure of the differences between predicted and actual values as a percentage. It is calculated as the average of the absolute differences between predicted and actual values, expressed as a percentage of the actual values. The formula for MAPE is given as:

$$ MAPE = \frac{100}{n} \sum_{i=1}^{n} \left| \frac{y_i - \hat{y_i}}{y_i} \right| $$

where $y_i$ represents the actual values, $\hat{y_i}$ represents the predicted values and $n$ represents the number of samples.

### R-Squared

R-Squared ($R²$) is a measure of the goodness of fit of a linear regression model. It is calculated as the ratio of explained variance to total variance. A higher R-Squared value indicates that a larger proportion of the variance in the dependent variable is explained by the independent variables. The formula for R-Squared is given as:

$$ R^2 = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y_i})^2}{\sum_{i=1}^{n} (y_i - \bar{y})^2} $$

where $y_i$ represents the actual values, $\hat{y_i}$ represents the predicted values, $\bar{y}$ represents the mean of the actual values, and $n$ represents the number of samples.
