# Discussion & Conclusion {#sec-discussion}

In this chapter, we discuss the results presented @sec-results with regard to our research questions defined in @sec-research-questions. Furthermore, we conclude by presenting the main challenges and giving recommendations for further research and practical implications of this study.

In @sec-research-questions, we defined the first main research question and two corresponding sub-questions as follows:

-   ***RQ1:** Which model or set of models can achieve the highest accuracy in estimating the heat energy consumption (HEC) of residential buildings?*

-   ***RQ1.1:** Can we achieve a higher accuracy in estimating heat energy consumption (HEC) of residential buildings compared to the current approach?*

-   ***RQ1.2:** Can we improve the predictions through feature engineering (e.g. adding new predictor variables) or by training models on different data subsets?*

The results of the model exploration presented in @sec-results-of-model-exploration showed that in our use case, the highest accuracy could be achieved with the AutoML approach. While the results with the AutoML approach were clearly better than with the custom approach, we did not find an unambiguous answer about the best performing AutoML algorithm. The best performing algorithm changed depending on the metric considered: While *GBM* generally provided good results with regard to RMSE and CV, other algorithms such as *Stacked Ensembles* and *XGB* could provide lower values for MAE and MAPE. However, with regard to RQ1 we can state that overall, the following algorithms provided the best results on a comparable level: *DRF, GBM, Stacked Ensembles* and *XGB*.

We showed in @sec-comparison-current-approach that the current approach overestimated the HEC on the test set by only 1.5% and also provides good results on municipal level in some cases. As illustrated in @fig-comparison-current-approach however, the algorithms of the AutoML approach provided a higher accuracy on the test set as well as on a aggregated level for a majority of municipalities. Thus we can conclude with regard to RQ1.1 that the current approach provides good results on a cantonal and in some cases also on municipal level, but the black-box models used in this study provide more accurate results on all levels (on all test data, per municipality and also per building).

@wenninger2021 provided results of different algorithms in the context of single and two-family buildings in Germany with CV values ranging from 0.33 to 0.35 and MAPE values from 27.5% to 33.0%. This can be compared to our results presented for the subsets on building class in @tbl-results-single-family-houses and @tbl-results-mfh-2-flats, where CV values are between 0.24 and 0.60 and MAPE values between 15.6% (GBM) and 39.7% (GLM).

@gubser2022 presented HEC prediction models on residential buildings in the cities of Biel, Geneva and St.Gallen and obtained CV values between 0.44 and 0.83 and MAPE values between 19% and 44% for the most accurate model (Random Forest Regressor). The metrics for all residential buildings in our use case as presented in @tbl-results-test-automl-different-predictors were in a similar range. However when modelling on subsets, the values decreased for CV (lowest: 0.20) as well as for MAPE (lowest: 12.9%).

Concerning RQ1.2, the results in @sec-subset-results indicated that modelling on data subsets does not improve the results in all cases. Training models for each construction period could only provide better results for some cases, while in other cases the MAPE was higher than the best MAPE using all data. By splitting the data into the three different survey years, the MAPE increased clearly. However, modelling on subsets by building class and municipality could improve the results and provide more accurate predictions in most cases.

The second main research question and its corresponding sub-questions were defined as follows:

-   ***RQ2:** What predictors are the most important for the prediction of HEC in the final model?*

-   ***RQ2.1:** What importance can be attributed to retrofit features?*

-   ***RQ2.2:** What importance can be attributed to socio-economic features in the model?*

In @sec-results-of-model-exploration we obtained a first hint regarding RQ2. By modelling with five different variable selections, we could show that the best accuracy is achieved without social indicators. However, we do not conclude that socio-economic factors do not influence the HEC, but rather that information on hectare level is not detailed enough to predict HEC for individual buildings. Since there was no socio-economic data available on building level, it was not possible to investigate further on this question. With regard to RQ2, the VIA in @sec-results-model-explainability indicated that, on a global level, the heated area is by far the most important predictor variable. Although other predictors had clearly lower influence on the model's prediction, the VIA attributed some importance to the municipality and the number of residents. Considering RQ2.1, we conclude that on a global level, only a low importance can be attributed to the retrofit information. However, the SHAP analysis of individual predictions illustrated that the information about retrofitting and building connectivity can have a substantial influence on individual predictions. During data preprocessing, the integration of retrofit information was a particular challenge. The raw data from the *Baselbieter Energiepaket* contained a lot of information and included different types of retrofit measures. In this study, we integrated the information as a binary variable if a building has been retrofitted or not. In @tbl-retrofit we could show that retrofitted buildings generally have a lower HEPI than non-retrofitted buildings. However, the effect of the different retrofit measures is not always evident.

From a more practical perspective, we can outline the following implications of this study for the cantonal energy statistics: First, the study provides a possible solution for the integration of additional data sources - in particular the information about retrofitting and building connectivity. These sources could be integrated into the statistics without a major methodological change of the current approach. Second, the study shows that differentiating between municipalities lead to better results and can reduce the estimation error on municipality level. Therefore, we recommend to consider differences between municipalities more explicitly in the current approach. Finally, @sec-comparison-current-approach illustrates that machine learning methods generally provide a higher estimation accuracy than the current approach. This finding should be discussed the context of future surveys. As a first step in this direction, we recommend using the approach of the this study for the next survey of the statistics and to compare the results with the current approach. This can serve as a decision basis for the further methodological development of the statistics.
