project:
  type: book
  
book:
  title: "Estimating the heat energy use of residential buildings"
  subtitle: "A case study in the Canton of Basel-Landschaft"
  author: Luca Hüsler
  submitted: 2023
  date: "today"
  chapters:
  - 00-management-summary.qmd
  - index.qmd
  - 00-list-of-abbrevations.qmd
  - 01-Introduction.qmd
  - 02-TheoreticalBackground.qmd
  - 03-Methodology.qmd
  - 04-Results.qmd
  - 05-Discussion_Conclusion.qmd
  - acknowledgements.qmd
  #- 99-references.qmd
  - declaration.qmd
  appendices:
  - 05-appendix.qmd
  references: references.qmd

bibliography: references.bib
csl: apa.csl
lot: true
lof: true

format:
  html:
    theme: cosmo
    title-block-banner: cover.png
  pdf:
    keep-tex: false
    toc-depth: 2
    toc: true
    # template-partials:
    #   - before-body.tex

prefer-html: true
number-sections: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true



# global definition of code chunk execution
execute:
  eval: true
  echo: false
  include: true
  cache: true
  warning: false
  message: false
  
  
# definiing location of figure and table captures
fig-cap-location: bottom
tbl-cap-location: bottom

extensions:
  - _extensions/_extension.yml

