project:
  type: book
  
book:
  title: "Estimating the heat energy use of residential buildings"
  subtitle: "A case study in the Canton of Basel-Landschaft"
  author: Luca Hüsler
  submitted: 2023
  date: "today"
  chapters:
    - index.qmd
    - abstract.qmd
    - declaration.qmd
    - acknowledgements.qmd
    #- 00-list-of-abbreviations
    - 01-Introduction.qmd
    - 02-TheoreticalBackground.qmd
    - 03-Methodology.qmd
    - 04-02_Descriptive_Statistics.qmd
    #- 04-03-Results_Model_Exploration.qmd
    #- 04-04_Results-Model_Subsets.qmd
    - 04-05-Results_Model_Sensitivity_Analysis.qmd
    - 05-Discussion_Conclusion.qmd
    - 99-references.qmd
  appendices:
    - 05-appendix.qmd
  references: references.qmd

bibliography: references.bib
csl: csl/apa.csl
lot: true
lof: true

format:
  html:
    theme: cosmo
    title-block-banner: cover.png
  pdf:
    keep-tex: false

prefer-html: true
number-sections: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true

# global definition of code chunk execution
execute:
  eval: true
  echo: false
  include: true
  cache: true
  warning: false
  
  
# definiing location of figure and table captures
fig-cap-location: bottom
tbl-cap-location: bottom

# font
