project:
  type: website
  output-dir: docs
  
book:
  title: "Estimating the heat energy use of residential buildings"
  subtitle: "A case study in the Canton of Basel-Landschaft"
  author: "Luca Hüsler"
  date: "today"
  chapters:
    - index.qmd
    - 01-Introduction.qmd
    - 02-TheoreticalBackground.qmd
    - 03-Methodology.qmd
    - 04-Results.qmd
    - 05-appendix.qmd
    - 99-references.qmd


bibliography: references.bib
csl: csl/apa.csl
lot: true
lof: true

format:
  html:
    theme: cosmo
    title-block-banner: cover.png
  pdf:
    documentclass: scrreprt

editor: visual

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true

